# Utiliser la dernière version d'Ubuntu comme base
FROM ubuntu:latest

# Mettre à jour la liste des paquets et mettre à jour les logiciels installés
RUN apt-get update
RUN apt-get upgrade -y

# Commande qui sera exécutée quand on lance un conteneur basé sur cette image
CMD ["echo", "Hello, World!"]
